--- #YAML:1.0
name:                POE-Component-SpreadClient
version:             0.05
abstract:            handle Spread communications in POE
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    POE:                           0.37
    POE::Session::AttributeBased:  0.07
    POE::Wheel::ReadWrite:         0
    Spread:                        3.17
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Apocalypse <APOCAL@cpan.org>
