---
name: POE-Component-SpreadClient
version: 0.07
author:
  - 'Apocalypse <APOCAL@cpan.org>'
abstract: Handle Spread communications in POE
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE: 0
  POE::Session: 0
  POE::Session::AttributeBased: 0
  POE::Wheel::ReadWrite: 0
  Spread: 3.017
  perl: 5.006
dynamic_config: 0
provides:
  POE::Component::SpreadClient:
    file: lib/POE/Component/SpreadClient.pm
    version: 0.07
  POE::Driver::SpreadClient:
    file: lib/POE/Driver/SpreadClient.pm
    version: 0.07
  POE::Filter::SpreadClient:
    file: lib/POE/Filter/SpreadClient.pm
    version: 0.07
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
