---
abstract: 'Handle Spread communications in POE'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SpreadClient
provides:
  POE::Component::SpreadClient:
    file: lib/POE/Component/SpreadClient.pm
    version: 0.09
  POE::Driver::SpreadClient:
    file: lib/POE/Driver/SpreadClient.pm
    version: 0.09
  POE::Filter::SpreadClient:
    file: lib/POE/Filter/SpreadClient.pm
    version: 0.09
requires:
  POE: 0
  POE::Session: 0
  POE::Session::AttributeBased: 0
  POE::Wheel::ReadWrite: 0
  Spread: 3.017
  constant: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
